### ISSUE TITLE
pdfLaTeX possible?

### ISSUE THREAD

**Issue by tecosaur** [HarveySheppard/yLaTeX#10]
Hello,

I recently stumbled across this and it looks fantastic! I'd love to use it for my documents. 
However, I have noticed that this seems to use XeLaTeX; given you seem to be a French speaker this makes sense as you can use `polyglossia` etc.
I am an (exclusively) English speaker so I do not share that requirement, and after trying out XeLaTeX once or twice I've returned to pdfLaTeX due to the significant difference in compile time I noticed.

So, do you know if it's possible, or how much modification I would have to do in order to use pdfLaTeX. I've somewhat fallen in love with the aesthetic and so dearly hope that this is feasible.

Thank you for providing such a wonderful package/style,

tecosaur

**Comment by HarveySheppard** [comment]
Hi tecosaur,

Glad to hear that you appreciate the packages on this repository!!

I definitely think you can modify the various packages of this repo to make them work with pdfLaTeX. Which of them would you be interested in? Some might be way easier than other to rewrite for pdfLaTeX (some might work out of the box, while others might be rather painful to transpile).

To make things clear: XeLaTeX is pdfLaTeX with support for system fonts (.otf and .ttf fonts) added on top of the LaTeX fonts, so XeLaTeX is a strict superset of pdfLaTeX.

Documents written for XeLaTeX can almost be compiled directly with pdfLaTeX. Here are the main required changes:

- stop using `fontenc` and `inputenc`
- use the `fontspec` package instead
- use `polyglossia` instead of `babel`
- remove all font related commands and replace them with their pdfLaTeX equivalent. Please note that all icons come from system fonts (`fontawesome` fonts). There exist a LaTeX version of the `fontawesome` font but I don't know if it is up-to-date and I used the last version of `fontawesome` in some of my packages, so you might need to use the older icon set which has less icons (you might not find good equivalent to some of the icons used basically)

To keep a similar visual style, you might want to look for fonts that look similar to the one used in the packages. I know that Roboto, Open Sans and a handful of other fonts were ported as LaTeX fonts.

In my personal opinion, you would be better off using XeLaTeX because adapting the packages will take you quite a bit of time and the gain is not substantial enough. But feel free to do as you please!

**Comment by tecosaur** [comment]
Thanks for the quick reply Harvey!

I happen to be a fan of Lato and so know that there's a working pdfLaTeX package, so that base is covered.
In terms of what I'm interested in using, at the moment I'm a particular fan of the look you achieved in [TM](https://github.com/HarveySheppard/yLaTeX/blob/master/examples/TM/TM_YvesZUMBACH_2014-2015.pdf) — particularly with the chapter pages and infoBulle. Though I'm likely to become interested in yLectureNote as well.

At the moment if it doesn't require too much effort to get the necessary packages working with pdfLaTeX I'm also considering tweaking it to my personal taste, so probably changing the colour scheme to a nice shade of emerald such as `#019875` and possibly (at least test) the IBM Plex font (also avalibe for pdfLaTeX).

Regarding your last sentence, would there be anything other that removing the extra font stuff required for 'adapting the packages' that you can anticipate?

**Comment by tecosaur** [comment]
Since the TM config is no longer maintained, do any of the currently maintained packages allow for the large contents and chapter pages, or a similar effect?

Regarding the use of fontawesome, I imagine I should be able to create a working package for the latest version using the method described [here](https://nek0.eu/posts/2017-07-21-How-to-use-OTF-fonts-with-pdflatex.html). Thoug if I end up using FA 5.5 I would still need to change the hex codes.

**Comment by HarveySheppard** [comment]
If you just want the modified table of content and chapter design, have a look at [this config](https://github.com/HarveySheppard/yLaTeX/tree/master/typographyArchive/tableOfContentAndChapter/bigGrayStrip). You will still need to tweak it a bit but it will probably represent a less work than the TM config (well, the config above is actually a simplified version of the TM config).

I did not know that `fontawesome5` existed. Thanks for pointing that out! You should definitely use it to replace the hex code with LaTeX commands.

**Comment by tecosaur** [comment]
I've just started trying to convert that to pdfLaTeX :) one quick question; do you know if there's something I can do so that I don't have to put `infoBulle` etc into the same folder?

**Comment by tecosaur** [comment]
Progress update: Have managed to successfully get the 'big grey strip' working :)

![image](https://user-images.githubusercontent.com/20903656/48334167-ab66f600-e694-11e8-878b-cc3a028d53ea.png)
![image](https://user-images.githubusercontent.com/20903656/48334183-b883e500-e694-11e8-8956-eb909595a254.png)

**Comment by tecosaur** [comment]
I'd be quite happy to share it, I'll just warn you that to get this I've written something closely customised to my personal taste/desires.

Yep! Commenting out the headers fixed it :)

I haven't added a margin paragraph. It seems that `marginnote` takes a margin size argument when used but I can't yet see how to set the margin size.

**Comment by HarveySheppard** [comment]
I am not sure I see exactly what you mean by adding dots to the chapter ToC. Anyway, ToC customization is performed using the `titletoc` package. You could look at `\dottedcontents`.

**Comment by tecosaur** [comment]
To clarify by dots I mean something like this

https://i.stack.imgur.com/NJgBH.png

**Comment by tecosaur** [comment]
### Update
Progress has been made, I'm doing most of this via my own class, which is nearing a state which I'm happy with.

**Comment by HarveySheppard** [comment]
Awesome! I look forward to see the end result!!

**Comment by HarveySheppard** [comment]
Hello tecosaur,

Did you have the chance to finish transitioning the TM class to pdfLaTeX? If you had, it would be awesome if you could share your improvements by sending me a pull request !!

**Comment by tecosaur** [comment]
I've been working on it, admittedly I think I've gone in a somewhat different direction to you since I've ended up with a ~800 line class file I've been refining with the odd `\RequirePackage{infobulle}` and having modified `infobulle` etc. to work as I want it to. I'm not sure how useful it will be, however, I'm happy to share what I've made and am currently in the process of getting it all together to put onto GitHub :)

**Comment by tecosaur** [comment]
Done. Take a look at [https://github.com/tecosaur/bmc](https://github.com/tecosaur/bmc).

Sorry for the long delay :stuck_out_tongue:

**Comment by HarveySheppard** [comment]
Nice work!! I love the style of the sections, it looks very material and I find this very interesting in a paper document!
