### ISSUE TITLE
Wonderful but unusable...

### ISSUE THREAD

**Issue by CIML-InstitutFresnel** [HarveySheppard/yLaTeX#4]
Dear Harvey,

your pdf is clearly wonderful but I'm not able to compile anything from your tex codes.
Could you help me please and help the community with your work?
Best regards.

**Comment by HarveySheppard** [comment]
Here are a few tips to make infoBulle work:

1: be sure you have the very last version of infoBulle (available at https://github.com/HarveySheppard/yLaTeX/tree/master/yPackages/infoBulle).

2: Then install the infoBulle package as described in my wiki (https://github.com/HarveySheppard/yLaTeX/wiki/Installing-custom-packages). If the package is installed correctly, you should be able to add "\usepackage{infoBulle}" in your document without having a "package not found" error (there might however be a different error!).

3: Then, be sure that you have the font "FontAwesome" (http://fontawesome.io/) installed system-wide on your computer (please install the .otf version as this format is computer oriented -- by opposition to web oriented -- and support all sort of useful features). You can check the font is available by trying to use it in LibreOffice (or Word if you don't have LibreOffice).

This should be enough to be able to compile infoBulle. However, if you still have problems, continue to step 4.

4: Once the font is installed, you need to find the name of the font on your system (Go to your font folder, right click on the font and ask for informations about it or open the font file by a specialized software and find the name out (you generally already have one of those softwares installed, otherwise, I recommend NexusFont if you are on Windows)). Generally it is "FontAwesome.otf" but it can sometimes be different.

5: Now open the infoBulle package file (infoBulle.sty) and change the line "\newfontfamily{\FA}{FontAwesome}" to "\newfontfamily{\FA}{<your font awesome font name without extension>}" under the "Font Configuration" section (around line 115, use a find and replace if ever).

And that's it! You normally have now a fully functional infoBulle package!

Please also note: for infoBulle to work, you absolutely need to compile your document using XeLaTeX and not PDFLaTeX! Don't worry, it changes almost nothing. XeLaTeX is a LaTeX compiler that allow to use latex fonts and system fonts. The syntax between PDFLaTeX and XeLaTeX is the same, only a few details change in the preambule (see http://tex.stackexchange.com/questions/21736/using-xelatex-instead-of-pdflatex)

Last note: once you understood how to install infoBulle, you can install almost all of my other package! Most of them require special fonts (that I provide in the "fonts" folder) that you have to install. All of them must be installed using the same procedure as the infoBulle.sty file, most of them require XeLaTeX.

**Comment by ambiso** [comment]
Unfortunately I can't get the example from [the yReport](https://github.com/HarveySheppard/yLaTeX/blob/master/yClass/yReport/README.md#starting-code) class working since many of the fonts can't be loaded (e.g. Fira Sans, Butler or Vollkorn).

Do you have any tips on how to make `xelatex` find these fonts? Most of them (except Butler for example) are in the [fonts](https://github.com/HarveySheppard/yLaTeX/tree/master/yClass/yReport/fonts) directory, still `xelatex` won't find and use them.

**Comment by HarveySheppard** [comment]
Hello @ambiso,

Sorry for not replying earlier, this week was a bit crazy...

Regarding the fonts, you need to install them system wide. If you can find them in programs like LibreOffice, then `xelatex` will find them too. On my Arch Linux, I put the files in `~/.local/share/fonts`, then run `fc-cache -fv` to update the font cache. The procedure is different on Windows and Mac.
