### ISSUE TITLE
\FA already defined error

### ISSUE THREAD

**Issue by Sabicool** [HarveySheppard/yLaTeX#8]
I installed the packages and relevant files but upon rendering the example report file using XeLaTex, the following error comes:

` LaTeX error: "xparse/command-already-defined"
! 
! Command '\FA' already defined!`

**Comment by moewew** [comment]
I hope this is the right place to report issues with `infoBulle.sty`, if not please ignore. See also https://tex.stackexchange.com/q/453188/35864.

The MWE
```
\documentclass{article}
\usepackage{infoBulle}
\begin{document}
Lorem
\end{document}
```
produces the error mentioned above.
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! LaTeX error: "xparse/command-already-defined"
! 
! Command '\FA' already defined!
! 
! See the LaTeX3 documentation for further information.
! 
! For immediate help type H <return>.
```

The culprit seems to be

https://github.com/HarveySheppard/yLaTeX/blob/12bad7f7cdd88193c6c221160d1b5ec50f43878c/yPackages/infoBulle/infoBulle.sty#L115

Which is superfluous after calling `\usepackage{fontawesome}`, since `fontawesome` issues `\newfontfamily{\FA}{FontAwesome}` itself in XeLaTeX/LuaLaTeX mode.

**Comment by HarveySheppard** [comment]
Thanks for pointing that out. The problem should now be fixed.

**Comment by moewew** [comment]
Thank you for the quick fix. I'm not a user of the package and don't have the required fonts installed, so I can't get back to you with any useful test results. So I will defer to @Sabicool to test the new release.
